name: college_hub
description: A new Flutter project.

# Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.17.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0

  english_words: ^4.0.0
  provider: ^6.0.5
  firebase_auth: ^4.9.0
  circular_chart_flutter: ^0.0.2
  cloud_firestore: ^4.9.1
  google_fonts: ^5.1.0
  sizer: ^2.0.15
  mailer: ^6.0.1
  collection: ^1.17.2
  firebase_core: ^2.15.1
  firebase_database: ^10.2.5
  firebase_messaging: ^14.6.7
  flutter_local_notifications: ^15.1.1
  fl_chart: ^0.63.0
  carousel_slider: ^4.2.1
  uuid: ^4.0.0
  

  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/
